device: 'cuda:0'
multi_gpu: false
gpus: [0]
model: 'identifier_model'
dataset: 'iam_word'
seed: 123456
img_height: 64
finetune: false


training:
  dset_name: 'iam_word'
  dset_split: 'test'
  epochs: 200
  lr_policy: 'linear'
  start_decay_epoch: 120
  n_epochs_decay: 80
  batch_size: 32
  # optimization:
  lr: 1.0e-3
  # sampling and saving
  print_iter_val: 20
  start_save_epoch_val: 20
  save_epoch_val: 4
  ckpt_dir: 'ckpts'
  n_class: 80
  sort_input: true
  resume: ~
  pretrained_backbone: './pretrained/wid_iam_spis_train64.pth'
  random_clip: true
  process_style: true
  frozen_backbone: true
  # Atomic export used only when validate_wier is enabled.
  export_writer_teacher: "./pretrained/wid_iam_spis_test64.pth"


valid:
  dset_split: 'test'
  batch_size: 256


StyBackbone:
  resolution: 16
  max_dim: 256
  in_channel: 1
  init: 'N02'
  dropout: 0.2
  norm: 'bn'


WidModel:
  n_writer: 161
  in_dim: 256
  init: 'none'
